name: Build-Plugin
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Headers
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path deps
          $zipPath = "obs-headers.zip"
          Invoke-WebRequest -Uri "https://github.com/obsproject/obs-studio/archive/refs/heads/master.zip" -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "temp_obs"
          # This moves all headers from the zip into your deps folder
          Get-ChildItem -Path "temp_obs/obs-studio-master/libobs/*.h" | Copy-Item -Destination "deps" -Force
          New-Item -ItemType File -Path "deps/obsconfig.h" -Force

      - name: Configure & Build
        shell: powershell
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INCLUDE_PATH="../deps"
          cmake --build . --config Release